### ISSUE TITLE
Error loading fonts over https

### ISSUE THREAD

**Issue by taimoorq** [hi5dev/google-webfonts#10]
When I move this gem to my production server (which is using https) I get the following error:

Mixed Content: The page at 'https://servername.com' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Raleway'. This request has been blocked; the content must be served over HTTPS.

Any way to add a flag that makes these requests get sent by https on certain environments?

**Comment by travishaynes** [comment]
Update to the latest version of the gem. It uses https by default now.
